Invalidating the containing widgets' cache when a widget changes
Victoire/victoire pull request #1065
Opened 2018-05-18 14:48 UTC by jdubuisson

## Type
Bugfix

## Purpose
This PR improves the cache management for nested widgets.
If widget A (say, a text) is nested (in the DOM) in widgetB (say, an image), the cache of widgetB needs to be refreshed when widgetA changes (ie : create, update, delete). This PR triggers this cache clear for any "parent" widget when a widget is created/updated/deleted.

The containing widgets id are collected on the preview page, then passed to the form modal. This is more robust than collecting the ids once the modal is open, should the front end structure change.

## BC Break
NO

2018-05-30 14:08 UTC, lenybernard requested changes

2018-05-30 14:08 UTC, lenybernard commented on Bundle/WidgetBundle/Model/WidgetManager.php
> +     * return array
```diff
- * return array
+ * @return array
```

2018-05-30 14:08 UTC, lenybernard commented on Bundle/CoreBundle/Resources/public/js/edit/widget.js
> +        var url = $vic(form).attr('action') + '?containerIds=' + containerIds.toString();
I don't like this, I'd prefer to do this sooner, in php. You need to put it in the `$actionParams` variable and let the route generator do its job : https://github.com/jdubuisson/victoire/blob/cc2dc679c6ed033d1317a04425bfcebbe56fc067/Bundle/WidgetBundle/Builder/WidgetFormBuilder.php#L238

2018-05-30 14:08 UTC, lenybernard commented on Bundle/WidgetBundle/Builder/WidgetFormBuilder.php
> +    public function renderNewForm($form, $widget, $slot, View $view, $quantum = null, $entity = null, $containerIds = null)
I wonder if it's normal you don't pass the $containerIds to the renderNewForm function here : https://github.com/jdubuisson/victoire/blob/cc2dc679c6ed033d1317a04425bfcebbe56fc067/Bundle/WidgetBundle/Builder/WidgetFormBuilder.php#L106 ?

2018-05-30 14:08 UTC, lenybernard commented on Bundle/WidgetBundle/Model/WidgetManager.php
> +        $containerIds = explode(',', $this->getRequest()->get('containerIds', null));
This line will probably be useless if you let php generate the route for the action instead of doing it with the toString javascript fn

2018-07-31 14:37 UTC, lenybernard commented
if you have some time one day @jdubuisson

2019-05-13 13:45 UTC, paulandrieux commented on Bundle/WidgetBundle/Model/WidgetManager.php
> +     * return array
```suggestion
     * @return array
```

2019-05-13 13:58 UTC, merged